### ISSUE TITLE
Adding a way to customize the download path

### ISSUE THREAD

**Issue by Fresh-glitch** [largestack/NAI-Extender#2]
**I love the extension so far!**

I have a little bit of a feature request, is it possible to make it so we can **customize the path the save image button saves to**?
I'd like to specify a path, though I don't think that's possible to do on the site at the moment.

Hope I'm not being too pushy or greedy ;w;

Have a great day 👍

**Comment by largestack** [comment]
Thanks @Fresh-glitch. Unfortunately chrome extensions can't access your filesystem so saving to a customized file path isn't going to be easily possible.

**Comment by Fresh-glitch** [comment]
I understand, thanks for the answer ^^
